---
abstract: 'Perl Utility for Recent Releases'
author:
  - 'Patrick Hochstenbach, C<< <patrick.hochstenbach at ugent.be> >>'
build_requires:
  Test::More: '1.001003'
  Test::Simple: '1.001003'
configure_requires:
  Module::Build::Tiny: '0.036'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu-Purr
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: '0.90'
  MetaCPAN::API::Tiny: '1.131730'
  Moo: '1.0'
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-Purr/issues
  homepage: https://github.com/LibreCat/Catmandu-Purr
  repository: https://github.com/LibreCat/Catmandu-Purr.git
version: '0.02'
